from utils.useract import UserActionType

{
    UserActionType.ContinueOpenModules: [
        "Ich will weitermachen",
        "Weiter lernen",
        "Abschnitt fertig machen",
        "Angefangene abschließen",
        "Was kann ich noch fertig machen?",
        "Welche Abschnitte sind noch nicht fertig?",
        "Was soll ich als nächstes machen?",
        "Gibt es noch offene Einheiten?",
        "Welches Kapitel sollte ich als Nächstes lesen?",
        "Welches Thema ist als Nächstes dran?",
        "Was kommt als nächstes dran?",
        "Welches Thema sollte ich als Nächstes vertiefen?",
        "Welche Module kommen als nächstes?",
        "Was steht als nächstes auf dem Lehrplan?",
        "Welches Thema sollte ich als nächstes angehen?",
        "Was sind meine nächsten Lernschritte?",
        "Was ist als nächstes auf meinem Lernweg geplant?",
        "Welches Thema sollte ich als Nächstes untersuchen?",
        "Welche Themen folgen auf dieses Modul?",
        "Was wäre als Nächstes auf meiner Lernliste?",
        "Was kann ich als nächstes erwarten?",
        "Was sollte ich als Nächstes erforschen?",
        "Welches Thema soll ich als nächstes angehen?",
        "Was ist das nächste Lernziel?",
        "Was kann ich als nächstes lernen?",
        "Welche Themen warten auf mich als nächstes?",
        "Was ist der nächste Kursinhalt?",
        "Welches Modul folgt als nächstes?",
        "Was ist das nächste Kapitel?",
        "Was sind die nächsten Schritte im Lernprozess?",
        "Was ist als Nächstes in meinem Lehrplan vorgesehen?",
        "Was sind die nächsten Lernziele?",
        "Was ist der nächste Abschnitt in meinem Lernprozess?",
        "Welches Thema ist als nächstes fällig?",
        "Welche Inhalte warten als nächstes auf mich?",
        "Was sollte ich als Nächstes in Angriff nehmen?",
        "Was kommt als nächstes in meinem Lernplan?",
        "Welches Wissen ist als nächstes dran?",
        "Was ist der nächste Themenblock?",
        "Was wird als nächstes behandelt?",
        "Welche Lektion sollte ich als Nächstes angehen?",
        "Welches Thema sollte ich als Nächstes bearbeiten?",
        "Was kann ich als nächstes in Angriff nehmen?",
        "Welches Thema kommt als Nächstes in meinem Studium?",
        "Welche Schwerpunkte sind als nächstes dran?",
        "Was ist die nächste Lektion auf meiner Lernliste?",
        "Welches Thema steht als Nächstes an?",
        "Was sind die nächsten Themen?",
        "Welches Thema kommt als nächstes dran?",
        "Was gibt es noch zu lernen?",
        "Welche Themen sind für mich als nächstes relevant?",
        "Wo geht es als nächstes weiter im Kurs?",
        "Was ist das nächste Modul in meiner Ausbildung?",
        "Was sind meine nächsten Lernziele?",
        "Was ist der nächste Lernabschnitt?",
        "Welche Lektion kommt nach dieser?",
        "Was ist das nächste Modul auf dem Programm?",
        "Welche Inhalte sind als nächstes geplant?",
        "Was steht als nächstes auf meiner Lernagenda?",
        "Wo geht es als nächstes weiter?",
        "Welche Inhalte kommen als nächstes?",
        "Was sollte ich als Nächstes studieren?",
        "Welche Lektionen warten als nächstes auf mich?",
        "Was ist das nächste Modul auf der Agenda?",
        "Was sind die nächsten Kapitel?",
        "Was sind die nächsten Lernmodule?",
        "Welche Themenbereiche kommen als nächstes?",
        "Welche Themenbereiche sind als nächstes dran?",
        "Welches Thema steht als nächstes an der Reihe?",
        "Welches Thema kommt als Nächstes dran?",
        "Wo kann ich weitere Lektionen finden?",
        "Was ist das nächste Modul, das ich bearbeiten kann?",
        "Welche weiteren Lektionen stehen zur Verfügung?",
        "Was kann ich noch lernen?",
        "Was sind meine nächsten Lernschritte?",
        "Was sind meine nächsten Möglichkeiten für das Lernen?",
        "Was sind meine Optionen für die nächste Lernphase?",
        "nächste",
        "Nächte Lektion",
        "Nächstes Modul",
        "Nächstes Kapitel",
        "weitermachen",
        "weiter lernen",
        "fertig machen"
    ],
    UserActionType.Search: [
        "Wo kann ich Infos zum Thema ... finden?",
        "Wo kann ich erfahren, wie man ... durchführt?",
        "Wo kann ich spezifische Anwendungen von ... finden?",
        "Wo kann ich Beispiele für ... finden?",
        "Wo kann ich Ressourcen über ... finden?",
        "Wo kann ich mehr über ... lernen?",
        "Wo kann ich Bücher über ... finden?",
        "Wo kann ich Grundlagen von ... finden?",
        "Wo kann ich Tutorials zu ... finden?",
        "Wo kann ich eine Einführung in ... finden?",
        "Wo kann ich Beispiele für ... finden?",
        "Wo kann ich mehr über ... erfahren?",
        "Wo kann ich eine einfache Erklärung für den Begriff ... finden?",
        "Wo finde ich Übungen zu ...?",
        "Wo finde ich Infos zu ...?",
        "Wo finde ich die Grundlagen von ...?",
        "Wo finde ich Artikel über ...?",
        "Wo finde ich Informationen über ...?",
        "Wo finde ich Videos, die ... erklären?",
        "Wo finde ich Bücher oder Artikel über ...?",
        "Wo finde ich Lernmaterialien zu ...?",
        "Wo steht was zu ...?",
        "Zeig mir Inhalte zu ...",
        "Wie führt man ... durch?",
        "Welche Informationsquellen gibt es zur ...?"
        "Könntest du mir erklären, was der Begriff ... bedeutet?",
        "Könntest du mir erklären, was ... bedeutet?",
        "Könntest du mir eine einfache Erklärung von ... geben?",
        "Könntest du mir eine kurze Erklärung für den Begriff ... geben?",
        "Kannst du mir eine Definition von ... geben?",
        "Kannst du mir eine kurze Beschreibung von ... geben?",
        "Kannst du mir eine präzise Erklärung geben, was mit ... gemeint ist?",
        "Ich verstehe den Begriff ... nicht. Kannst du ihn erklären?",
        "Was ist das Ziel der ... und wie wird es erreicht?",
        "Was ist die Bedeutung von ...?",
        "Was ist mit ... gemeint?",
        "Was ist ...?",
        "Was ist die Definition von ...?",
        "Was sind die grundlegenden Konzepte hinter der ...?",
        "Was bezeichnet man als ...?",
        "suchen",
        "finden",
        "Definition",
        "Bedeutung",
        "erklären"
    ],
    UserActionType.RequestHelp: [
        "Hilfe",
        "Was kann ich sagen?",
        "Wie benutze ich dich?",
        "Anleitung",
        "Wie kann ich dich steuern?"
        "Welche Aufgaben sind für dich geeignet?",
        "Wie kann ich dich anweisen?",
        "Welche Aufgaben kannst du erledigen?",
        "Brauche Rat und Beistand.",
        "Wäre nett, wenn du mir helfen könntest.",
        "Kannst du mir Orientierung geben?",
        "Benötige deinen Rat und deine Hilfe.",
        "Wäre dankbar für deine Ratschläge.",
        "Kannst du mir eine Lösung präsentieren?",
        "Kannst du mich beraten?",
        "Was kannst du eigentlich?",
        "Kannst du mir helfen?",
        "Kannst du mir Lösungen bieten?",
        "Was kannst du mir bieten?",
        "Wie kann ich dich einsetzen?",
        "Kannst du mir assistieren?",
        "Bin auf Hilfe angewiesen.",
        "Was kannst du für mich tun?",
        "Welche Funktionen hast du?",
        "Was sind deine besonderen Fähigkeiten?",
        "Hilfe",
        "Was sind deine Eigenschaften?",
        "Was sind deine Grenzen?",
        "Kannst du mich beraten und unterstützen?",
        "Kannst du mir weiterhelfen?",
        "Welche Funktionen stehen mir zur Verfügung?",
        "Wie kann ich dich nutzen?",
        "Wäre toll, wenn du mir helfen könntest.",
        "Wäre dankbar für deine Hilfe und Unterstützung.",
        "Kannst du mir dabei helfen, etwas zu tun?",
        "Was sind deine Stärken?",
        "Was kann ich mit dir machen?",
        "Was für Funktionen hast du?",
        "Was für eine Art von Aufgaben kannst du bewältigen?",
        "Brauche Unterstützung!",
        "Wie kann ich dich verwenden?",
        "Kannst du mir bei etwas helfen?",
        "Wäre dankbar für deine Hilfe.",
        "Wie funktionierst du?",
        "Kannst du mich unterstützen?",
        "Habe Schwierigkeiten, kannst du mich unterstützen?",
        "Kannst du mir beistehen?",
        "Kannst du mir helfen, eine bestimmte Aufgabe zu erledigen?",
        "Habe Fragen, kannst du helfen?",
        "Wie kann ich dich konfigurieren?",
        "Welche Anweisungen verstehst du?",
        "Was hast du zu bieten?",
        "Wie kann ich dich optimieren?",
        "Brauche Anleitung, kannst du helfen?",
        "Benötige Hilfe bei meinem Problem.",
        "Wie kann ich dich bedienen?",
        "Kannst du mich begleiten?",
        "Wie kann ich dich programmieren?",
        "Wäre toll, wenn du mich unterstützen könntest.",
        "Kannst du mir Tipps geben?",
        "Wie kann ich dich benutzen?",
        "Kannst du mir zur Seite stehen?",
        "Kannst du mich aufklären und unterstützen?",
        "Wie weit reichen deine Fähigkeiten?",
        "Wie arbeitest du?",
        "Wie kann ich deine Fähigkeiten nutzen?",
        "Ich stecke fest, kannst du helfen?",
        "Benötige Hilfe hier!",
        "Was sind deine Möglichkeiten?",
        "Was sind deine Fähigkeiten?",
        "Brauche Hilfe bei dieser Aufgabe.",
        "Ich könnte eine Hand gebrauchen.",
        "Benötige deinen Input und Rat.",
        "Was kann ich tun?",
        "Wie kann ich dich verbessern?",
        "steuern",
        "helfen"
    ],
    UserActionType.RequestSettings: [
        "Einstellungen",
        "Einstellungen verwalten"
        "Einstellungen anzeigen"
        "Einstellungen ändern",
        "Einstellungen bearbeiten",
        "Ändere meine Einstellungen",
        "Pass meine Einstellungen an",
        "Einstellungen verändern, bitte",
        "Ich möchte meine Einstellungen modifizieren",
        "Einstellungen anpassen",
        "Kann ich meine Einstellungen konfigurieren?",
        "Einstellungen ändern, wenn möglich",
        "Ich will die Einstellungen editieren",
        "Verwalte meine Einstellungen, bitte",
        "Verwalte meine Einstellungen",
        "Ändere meine Konfiguration",
        "Modifiziere meine Einstellungen",
        "Einstellungen aktualisieren, bitte",
        "Einstellungen aktualisieren",
        "Pass meine Voreinstellungen an",
        "Bearbeite meine Einstellungen",
        "Kann ich meine Optionen anpassen?",
        "Verändere meine Einstellungen nach Bedarf",
        "Ich würde gerne meine Einstellungen anpassen",
        "Passt du meine Einstellungen an?",
        "Einstellungen modifizieren, falls nötig",
        "Könnten wir meine Einstellungen anpassen?",
        "Ändere bitte meine Einstellungen",
        "Verwalte meine Optionen",
        "Kannst du meine Voreinstellungen ändern?",
        "Ich möchte meine Einstellungen überarbeiten",
        "Pass meine Optionen nach meinen Wünschen an",
        "Einstellungen nach meinen Präferenzen gestalten",
        "Ich will meine Einstellungen anpassen",
        "Könntest du meine Konfiguration ändern?",
        "Bearbeite bitte meine Einstellungen",
        "Modifiziere meine Voreinstellungen",
        "Einstellungen nach meinen Anforderungen ändern",
        "Kannst du meine Optionen aktualisieren?",
        "Ändere bitte meine Konfiguration",
        "Pass meine Einstellungen meinen Vorlieben an",
        "Ich möchte meine Optionen verändern",
        "Einstellungen an meine Bedürfnisse anpassen",
        "Verwalte bitte meine Konfiguration",
        "Ich würde gerne meine Optionen überprüfen",
        "Ändere bitte meine Einstellungen entsprechend",
        "anpassen",
        "verwalten"
    ],
    UserActionType.RequestNextSection: [
        "Was Neues lernen",
        "Woanders weitermachen",
        "Andere Inhalte",
        "Neues anfangen",
        "Mit dem nächsten Thema beginnen",
        "Was gibt es noch?"
        "Was sind meine weiteren Lernmöglichkeiten?",
        "Welche weiteren Lernmaterialien gibt es?",
        "Gibt es noch andere Themen?",
        "Welche anderen Themenbereiche gibt es?",
        "Welche anderen Themen sind noch relevant für meine Ausbildung?",
        "Welche anderen Themen gibt es noch?",
        "Kann ich weitere Lernmöglichkeiten nutzen?",
        "Gibt es noch weitere Lerneinheiten?",
        "Kannst du mir andere Lerninhalte empfehlen?",
        "Gibt es andere Lernmodule, die ich angehen kann?",
        "Was sind meine Alternativen für das nächste Modul?",
        "Welche anderen Einheiten gibt es noch?",
        "Was sind meine alternativen Lernmöglichkeiten?",
        "Welche weiteren Lernquellen stehen zur Verfügung?",
        "Welche anderen Module stehen zur Verfügung?",
        "Welche weiteren Themen und Module sind für mich relevant?",
        "Welche anderen Themen sind noch relevant?",
        "Was kann ich noch tun?",
        "Was gibt es noch, was ich erforschen kann?",
        "Was gibt es noch, um mein Wissen zu erweitern?",
        "Welche anderen Themen stehen zur Verfügung?",
        "Welche anderen Inhalte gibt es?",
        "Gibt es noch andere Themen, die für mich relevant sind?",
        "Was ist der nächste Bereich, den ich erforschen kann?",
        "Was gibt es noch, was ich lernen kann?",
        "Was gibt es noch zu lernen?",
        "Welche weiteren Möglichkeiten stehen mir zur Verfügung?",
        "Welche Inhalte stehen mir noch zur Verfügung?",
        "Kannst du mir weitere Lerninhalte zur Verfügung stellen?",
        "Was kann ich sonst noch lernen, um meine Fähigkeiten zu verbessern?",
        "Welche weiteren Lerninhalte sind für mich verfügbar?",
        "Welche Optionen habe ich für mein Lernprogramm?",
        "Welche Themen sind noch offen?",
        "Gibt es noch andere Module, die ich absolvieren kann?",
        "Welche anderen Themen können mir helfen, meine Ziele zu erreichen?",
        "Welche anderen Themen sind in meinem Lernprogramm enthalten?",
        "Welche anderen Kapitel kann ich studieren?",
        "Was kann ich sonst noch machen?",
        "Welche weiteren Themen stehen zur Verfügung?",
        "Was sind meine Optionen für weitere Lerninhalte?",
        "Gibt es andere Module, die mich interessieren könnten?",
        "Was sind meine anderen Möglichkeiten, um mehr zu lernen?",
        "Was sind meine Alternativen?",
        "Was sind meine Möglichkeiten, um weiterzulernen?",
        "Gibt es weitere Themen, die ich erkunden kann?",
        "Was sind die anderen verfügbaren Lernressourcen?",
        "Gibt es andere Module, die für mich geeignet sind?",
        "Welche anderen Themenbereiche kann ich erkunden?",
        "Gibt es andere Module, die mich herausfordern könnten?",
        "andere",
        "Alternativen",
        "neues"
    ],
    UserActionType.RequestReview: [
        "Ich will was wiederholen",
        "Alte wiederholen",
        "Was sollte ich nochmal anschauen?",
        "Wo kann ich mich noch verbessern?",
        "Welche Themen sind für mich noch neu?"
        "Wo brauche ich noch mehr Übung und Vertiefung?",
        "Welche Bereiche sollten noch vertieft werden?",
        "Wo sollte ich noch mehr Zeit investieren?",
        "Gibt es noch Themen, die ich nicht ausreichend verstanden habe?",
        "Wo kann ich noch wachsen und mich weiterentwickeln?",
        "Wo benötige ich noch Unterstützung?",
        "Welche Themenbereiche sollte ich noch angehen?",
        "In welchen Bereichen sollte ich mich noch weiterbilden?",
        "Wo sehe ich noch Verbesserungspotenzial?",
        "Wo kann ich noch mehr lernen?",
        "In welchen Themenbereichen sollte ich noch mehr Erfahrung sammeln?",
        "In welchen Bereichen kann ich noch dazulernen?",
        "In welchen Einheiten sollte ich noch stärker werden?",
        "Wo habe ich noch Defizite?",
        "Wo habe ich noch Lücken in meinem Wissen?",
        "Welche Module sollten noch bearbeitet werden?",
        "Wo kann ich meine Kenntnisse noch erweitern?",
        "Wo muss ich noch mehr Zeit investieren?",
        "Wo sollte ich meine Kenntnisse noch verbessern?",
        "In welchen Bereichen bin ich noch nicht so stark?",
        "In welchen Einheiten habe ich noch Lernbedarf?",
        "Wo kann ich meine Fähigkeiten noch ausbauen?",
        "In welchen Bereichen sollte ich noch weiterhin arbeiten?",
        "Wo kann ich meine Fähigkeiten noch stärker ausbauen?",
        "Welche Themen sollte ich noch intensiver behandeln?",
        "Wo habe ich noch Schwierigkeiten?",
        "Wo gibt es noch Potenzial für Verbesserungen?",
        "Auf welchen Gebieten benötige ich noch mehr Übung?",
        "Wo liegen noch meine Schwächen?",
        "In welchen Einheiten sollte ich noch weiter lernen?",
        "Welche Themen erfordern noch mehr Aufmerksamkeit von mir?",
        "Welche Themen sind für mich noch herausfordernd?",
        "Wo habe ich noch Entwicklungspotential?",
        "Welche Themen sollten noch behandelt werden?",
        "Wo fehlt mir noch Wissen?",
        "Wo muss ich mich noch verbessern?",
        "Wo sollte ich noch weiter lernen?",
        "In welchen Bereichen brauche ich noch mehr Unterstützung?",
        "Wo habe ich noch Herausforderungen?",
        "Wo kann ich noch Fortschritte erzielen?",
        "Wo kann ich noch dazulernen?",
        "Welche Bereiche sollte ich noch weiter ausbauen?",
        "Gibt es bestimmte Module, die ich noch einmal durchgehen sollte?",
        "In welchen Bereichen benötige ich noch Übung?",
        "Wo kann ich noch Wissen aufbauen?",
        "Welche Themen sollte ich noch vertiefen?",
        "Wo habe ich noch Wissenslücken?",
        "Welche Bereiche benötigen noch Aufmerksamkeit und Übung?",
        "In welchen Bereichen muss ich noch mehr tun?",
        "Welche Themen sollten noch vertieft werden?",
        "In welchen Themen kann ich mich noch steigern?",
        "In welchen Themenbereichen sollte ich noch Fortschritte machen?",
        "Wo gibt es noch Lücken in meinem Wissen?",
        "Wo liegen meine Schwächen und wo kann ich mich noch verbessern?",
        "Gibt es noch Bereiche, in denen ich mich unsicher fühle?",
        "Welche Bereiche benötigen noch meine Aufmerksamkeit?",
        "Wo sollte ich meine Bemühungen verstärken?",
        "Welche Bereiche sollten noch stärker bearbeitet werden?",
        "In welchen Einheiten brauche ich noch mehr Übung?",
        "Wo kann ich noch mehr Kenntnisse erlangen?",
        "Wo gibt es noch Nachholbedarf für mich?",
        "Wo kann ich meine Fertigkeiten noch verbessern?",
        "Welche Fähigkeiten sollten noch trainiert werden?",
        "Wo gibt es noch Verbesserungspotenzial für mich?",
        "Wo kann ich noch bessere Ergebnisse erzielen?",
        "Welche Bereiche sollten noch mehr beachtet werden?",
        "In welchen Einheiten kann ich noch dazulernen?",
        "In welchen Bereichen fehlt mir noch Wissen?",
        "verbessern",
        "Kann ich die Inhalte eines bestimmten Moduls erneut durchgehen?",
        "Wo finde ich die Themen, die ich bereits bearbeitet habe?",
        "Kann ich die Einheiten, die ich bereits bearbeitet habe, noch einmal durchgehen?",
        "Welche Einheiten müssen noch einmal betrachtet werden?",
        "In welchem Bereich muss ich noch einmal üben, um mich zu verbessern?",
        "Kann ich noch einmal durch einen bestimmten Abschnitt gehen?",
        "Welche Themen sollten noch einmal geübt werden, um meine Kenntnisse zu verbessern?",
        "Welche Themen sollte ich noch einmal üben?",
        "Welches Kapitel sollte ich noch einmal ansehen?",
        "In welchen Bereichen benötige ich nochmal Unterstützung und Übung?",
        "Was kann ich wiederholen?",
        "Was ist das nächste, was ich noch einmal wiederholen sollte?",
        "Welche Lerninhalte brauchen noch einmal Wiederholung?",
        "Welches Thema sollte ich noch einmal betrachten?",
        "Kann ich die Einheiten, noch einmal durchgehen?",
        "Welches Thema kann ich noch einmal durchgehen?",
        "Welche Lektionen sollte ich mir erneut anschauen?",
        "In welchen Bereichen benötige ich nochmal Übung?",
        "Welches Thema sollte ich noch einmal angehen?",
        "Welche Lektionen sollten noch einmal durchgegangen werden?",
        "In welchen Bereichen sollte ich meine Fähigkeiten nochmal verbessern?",
        "Was sind die Module, die ich noch einmal durchgehen sollte?",
        "Gibt es Module, die ich noch einmal durchgehen sollte?",
        "In welchen Bereichen sollte ich nochmal üben?",
        "Welche Lektionen sollte ich noch einmal ansehen?",
        "Kann ich noch einmal eine bestimmte Einheit üben?",
        "Welches Thema braucht noch einmal Aufmerksamkeit?",
        "Wo kann ich die Themen finden, die ich bereits behandelt habe?",
        "Was sind die Bereiche, in denen ich noch Übung brauche?",
        "Welche Lernmodule sollten noch einmal durchgegangen werden?",
        "Was kann ich noch einmal wiederholen?",
        "Welche Themen sollten noch einmal wiederholt werden?",
        "Welche Lektionen sollten nochmal durchgegangen werden?",
        "Gibt es Einheiten, die ich wiederholen sollte?",
        "Gibt es Module, die ich nochmal durchgehen sollte?",
        "Wo finde ich die Themen, die ich bereits behandelt habe?",
        "Welche Themen sollte ich nochmal bearbeiten?",
        "Was ist das nächste Thema, das ich noch einmal betrachten sollte?",
        "Welche Themen benötigen noch einmal Aufmerksamkeit?",
        "Welche Themen sollten noch einmal durchgegangen werden?",
        "Welche Bereiche benötigen noch einmal Aufmerksamkeit?",
        "In welchen Bereichen habe ich Schwierigkeiten und sollte diese nochmal üben?",
        "Wo finde ich die Module, die ich bereits abgeschlossen habe?",
        "Welche Lerninhalte können noch einmal durchgegangen werden?",
        "In welchem Bereich sollte ich noch einmal meine Fähigkeiten verbessern?",
        "Was sind meine Optionen zum Wiederholen?",
        "Welches Modul kann ich noch einmal durchgehen, um mich zu verbessern?",
        "Was sind die Themen, die ich noch einmal durchgehen sollte?",
        "In welchen Bereichen benötige ich noch Übung?",
        "Was sind die Lernmodule, die ich wiederholen kann?",
        "Welches Thema sollte ich mir noch einmal ansehen?",
        "Gibt es Einheiten, die ich noch einmal durchgehen sollte?",
        "Kann ich die Inhalte eines bestimmten Moduls noch einmal durchgehen?",
        "Welche Themen sollten erneut behandelt werden?",
        "Welche Themen sollte ich nochmal durchgehen?",
        "Welche Module sollten noch einmal bearbeitet werden?",
        "Welche Lektionen sollten noch einmal betrachtet werden?",
        "Kann ich noch einmal durch eine bestimmte Lektion gehen?",
        "Wo kann ich die Inhalte eines bestimmten Moduls erneut durchgehen?",
        "Welche Bereiche sind noch schwierig für mich und sollten nochmal geübt werden?",
        "In welchem Bereich kann ich noch einmal üben?",
        "Wo kann ich die Einheiten finden, die ich bereits bearbeitet habe?",
        "Wo finde ich die Einheiten, die ich bereits abgeschlossen habe?",
        "Welches Modul könnte ich noch einmal durcharbeiten?",
        "Welche Einheiten sollten noch einmal wiederholt werden?",
        "Wo kann ich die Lektionen erneut anschauen?",
        "In welchem Bereich sollte ich noch einmal üben?",
        "Welches Thema soll ich noch einmal durchgehen?",
        "Kann ich mich noch einmal in ein Thema vertiefen?",
        "Welche Module kann ich noch einmal durchgehen?",
        "Gibt es ein bestimmtes Modul, das ich noch einmal durcharbeiten sollte?",
        "wiederholen",
        "erneut",
        "nochmal",
        "noch einmal",
        "bereits"
    ],
    UserActionType.RequestForumPosts: [
        "Gibt es neue Nachrichten?",
        "Was gibts neues im Forum?",
        "Sollte ich mal wieder ins Forum schauen?",
        "Nachrichten",
        "Was habe ich verpasst?",
        "Sind neue Beiträge verfügbar?",
        "Gibt es aktuelle Nachrichten im Forum?",
        "Zeig mir bitte die neuesten Forenbeiträge",
        "Hast du Informationen über aktuelle Diskussionen?",
        "Gibt es neue Einträge im Forum?",
        "Welche Neuigkeiten gibt es im Forum?",
        "Gibt es aktuelle Forenaktivitäten?",
        "Zeig mir die letzten Forumseinträge",
        "Sind frische Nachrichten im Forum verfügbar?",
        "Was gibt es Neues in den Foren?",
        "Gibt es kürzlich aktualisierte Forenthemen?",
        "Welche Diskussionen sind in letzter Zeit aufgekommen?",
        "Zeige mir die aktuellsten Forenbeiträge, bitte",
        "Hast du Informationen über neu gestartete Diskussionen?",
        "Gibt es frische Beiträge im Forum?",
        "Was hat sich im Forum getan?",
        "Sind neue Nachrichten in den Foren veröffentlicht worden?",
        "Zeig mir die neuesten Diskussionen im Forum",
        "Gibt es Aktualisierungen in den Foren?",
        "Hast du Infos über die jüngsten Forenbeiträge?",
        "Gibt es kürzlich eingestellte Nachrichten im Forum?",
        "Zeige mir aktuelle Themen im Forum",
        "Gibt es Neuigkeiten von den Forenmitgliedern?",
        "Sind neue Beiträge in den Diskussionen aufgetaucht?",
        "Was ist kürzlich im Forum passiert?",
        "Gibt es frische Informationen in den Forenbeiträgen?",
        "Zeig mir die jüngsten Forenupdates",
        "Gibt es aktuelle Diskussionen im Forum?",
        "Hast du Infos über die letzten Forennachrichten?",
        "Gibt es neue Entwicklungen im Forum?",
        "Zeige mir bitte die neuesten Themen im Forum",
        "Was gibt es Neues in den Forendiskussionen?",
        "Gibt es frische Beiträge in den Foren?",
        "Sind in letzter Zeit neue Diskussionen entstanden?",
        "Welche Themen sind kürzlich im Forum aufgekommen?",
        "Gibt es Neuigkeiten in den Forenbeiträgen?",
        "Zeige mir die aktuellsten Forenupdates",
        "Gibt es kürzlich veröffentlichte Nachrichten im Forum?",
        "Was gibt es Neues in den Diskussionen?",
        "Hast du Informationen über aktuelle Forenbeiträge?",
        "Forum",
        "Posts"
    ],
    UserActionType.RequestDeadlines: [
        "Wann ist die nächste Abgabe?",
        "Was sollte ich dringend fertig machen?",
        "Gibt es demnächst Abgaben?",
        "Abgaben",
        "Wann steht die nächste Abgabe an?",
        "Gibt es demnächst Fristen für Abgaben?",
        "Wann muss die nächste Aufgabe abgegeben werden?",
        "Kannst du mir sagen, wann die nächste Abgabe fällig ist?",
        "Gibt es in absehbarer Zeit Hausaufgaben?",
        "Wann ist der Abgabetermin für die nächste Aufgabe?",
        "Hast du Informationen zu anstehenden Abgaben?",
        "Wann steht die nächste Abgabefrist bevor?",
        "Gibt es demnächst etwas, das abgegeben werden muss?",
        "Wann muss ich die nächste Aufgabe einreichen?",
        "Wann ist die Deadline für die nächste Aufgabe?",
        "Gibt es bald anstehende Abgaben?",
        "Wann sollte ich die nächste Arbeit einreichen?",
        "Hast du Infos über anstehende Abgabetermine?",
        "Wann muss ich die nächste Aufgabe erledigen?",
        "Gibt es demnächst eine Aufgabenabgabe?",
        "Wann steht die nächste Abgabe bevor?",
        "Hast du Details zur nächsten Abgabefrist?",
        "Gibt es in naher Zukunft abzugebende Aufgaben?",
        "Wann ist die nächste Abgabe fällig?",
        "Kannst du mir sagen, wann die nächste Aufgabe zu tun ist?",
        "Gibt es demnächst Termine für Abgaben?",
        "Wann muss ich das nächste Projekt einreichen?",
        "Hast du Informationen über anstehende Aufgaben?",
        "Wann ist die nächste Abgabedeadline?",
        "Gibt es demnächst anstehende Aufgaben?",
        "Wann ist der Termin für die nächste Abgabe?",
        "Hast du den Zeitpunkt für die nächste Aufgabe?",
        "Gibt es bald anstehende Hausaufgaben?",
        "Wann muss ich die nächste Arbeit abgeben?",
        "Kannst du mir sagen, wann die nächste Abgabe ansteht?",
        "Gibt es in Kürze abzugebende Arbeiten?",
        "Wann sollte ich mich auf die nächste Aufgabe vorbereiten?",
        "Gibt es demnächst zu erledigende Hausaufgaben?",
        "Wann ist die nächste Abgabe erforderlich?",
        "Hast du Informationen über kommende Aufgaben?",
        "Wann ist die nächste Aufgabe zu erledigen?",
        "Gibt es bald anstehende Aufgaben?",
        "Wann ist die Deadline für die nächste Arbeit?",
        "Kannst du mir sagen, wann die nächste Abgabe notwendig ist?",
        "Wann"
    ],
    UserActionType.RequestProgress: [
        "Wie weit bin ich schon?",
        "Wie viel fehlt noch im Kurs?",
        "Wie viel hab ich schon erledigt?",
        "Wie ist mein Fortschritt?",
        "Wie viele Kapitel muss ich noch bewältigen?",
        "Wie viele Lektionen sind noch übrig?",
        "Wie viele Module gibt es?",
        "Wie viele Einheiten muss ich noch absolvieren, bevor der Kurs abgeschlossen ist?",
        "Kannst du mir sagen, wie viele Abschnitte noch vor mir liegen?",
        "Wie viele Themen muss ich noch lernen, bevor der Kurs beendet ist?",
        "Wie viele Lernabschnitte muss ich noch durchgehen?",
        "Wie viele Module sind noch übrig?",
        "Wie viele Einheiten stehen noch an?",
        "Wie viele Module gibt es noch zu durchlaufen?",
        "Wie viele Abschnitte muss ich noch durchgehen?",
        "Wie viele Abschnitte beinhaltet das Programm?",
        "Wie viele Teile hat der Kurs?",
        "Wie viele Lerninhalte warten noch auf mich?",
        "Wie viele Lerneinheiten stehen noch aus?",
        "Wie viele Unterrichtseinheiten sind noch zu absolvieren?",
        "Wie viele Kapitel muss ich noch durchgehen?",
        "Wie viele Themenblöcke muss ich noch durchgehen?",
        "Wie viele Schritte fehlen noch bis zum Ende?",
        "Wie viele Kapitel gibt es insgesamt?",
        "In wie viele Bereiche ist der Kurs unterteilt?",
        "Wie viele Kapitel muss ich noch lernen?",
        "Wie viele Themen muss ich noch lernen?",
        "Wie viele Themen muss ich noch durchgehen?",
        "Gibt es noch weitere Einheiten, die ich durchlaufen muss?",
        "Gibt es noch weitere Teile des Kurses, die ich durchlaufen muss?",
        "Wie viele Lektionen beinhaltet der Kurs?",
        "Wie viele Lernmodule sind noch übrig?",
        "Wie viele Abschnitte gibt es in diesem Kurs?",
        "Wie viele Kurseinheiten muss ich noch absolvieren?",
        "Wie viele Abschnitte muss ich noch absolvieren?",
        "Wie viele Lektionen habe ich noch zu absolvieren?",
        "Wie viele Einheiten sind noch übrig?",
        "Wie viele Themenbereiche gibt es insgesamt?",
        "Wie viele Kurseinheiten muss ich noch bearbeiten?",
        "Wie viele Einheiten sind noch zu absolvieren?",
        "Wie viele Schritte sind noch zu absolvieren?",
        "Wie viele Lernmodule gibt es noch zu bearbeiten?",
        "Wie viele Schritte sind noch zu durchlaufen?",
        "Wie viele Unterrichtseinheiten sind noch übrig?",
        "Wie weit bin ich in dem Kurs fortgeschritten?",
        "Kannst du mir sagen, wie viele Lernmodule noch vor mir liegen?",
        "Wie viele Module gibt es insgesamt?",
        "Wie viele Lerneinheiten muss ich noch durchgehen?",
        "Wie viele Kapitel habe ich bereits durchgelesen?",
        "Wie viele Abschnitte sind noch übrig?",
        "Wie viele Abschnitte habe ich bereits abgeschlossen?",
        "Wie viele Lernmodule habe ich noch vor mir?",
        "Wie viele Lernstufen gibt es noch?",
        "Wie viele Abschnitte sind noch zu durchlaufen?",
        "Wie viele Lektionen müssen noch gelernt werden?",
        "Wie viele Module gibt es insgesamt in diesem Kurs?",
        "Wie viele Einheiten muss ich noch abschließen?",
        "Wie viele Themen gibt es noch zu bewältigen?",
        "Wie viele Lektionen gibt es insgesamt in diesem Kurs?",
        "Wie viele Teile muss ich noch absolvieren?",
        "Wie viele Lernschritte fehlen noch bis zum Abschluss?",
        "Wie viele Lerninhalte sind noch zu bearbeiten?",
        "Wie viele Einheiten habe ich noch nicht abgeschlossen?",
        "Gibt es eine Übersicht der Lerneinheiten?",
        "Wie viele Lerninhalte gibt es insgesamt in diesem Kurs?",
        "Gibt es noch weitere Module, die ich durchlaufen muss?",
        "Gibt es noch weitere Lerninhalte, die ich absolvieren muss?",
        "Kannst du mir sagen, wie viele Module ich noch durchgehen muss?",
        "Wie viele Module habe ich bereits absolviert und wie viele sind noch übrig?",
        "Wie viele Einheiten gibt es noch zu bearbeiten?",
        "Kannst du mir sagen, wie viele Themen ich noch durchgehen muss?",
        "Wie viele Kapitel sind noch zu absolvieren?",
        "Wie viele Themen habe ich bereits gelernt?",
        "Gibt es noch weitere Themen, die ich durchgehen muss?",
        "Wie viele Lerninhalte muss ich noch durchgehen?",
        "Wie viele?"

    ],
    UserActionType.RequestBadgeProgress: [
        "Was muss ich machen um den nächsten Badge zu bekommen?",
        "Was fehlt noch bis zum nächsten Badge?",
        "Wie ist mein Badge Fortschritt?",
        "Wie kriege ich den nächsten Badge?",
        "Welche Schritte sind erforderlich, um den nächsten Badge zu erhalten?",
        "Was muss ich tun, um den nächsten Badge zu verdienen?",
        "Wie sieht mein Fortschritt für den nächsten Badge aus?",
        "Welche Aufgaben stehen an, um den nächsten Badge zu erreichen?",
        "Kannst du mir sagen, was ich tun muss, um den nächsten Badge zu bekommen?",
        "Wie sieht es mit meinem Badge-Fortschritt aus?",
        "Welche Anforderungen gibt es für den nächsten Badge?",
        "Was sind die Schritte, um meinen Badge zu verbessern?",
        "Wie kann ich meinen Fortschritt für den nächsten Badge überprüfen?",
        "Welche Maßnahmen sind notwendig, um den nächsten Badge zu erreichen?",
        "Was sind die Kriterien für den nächsten Badge?",
        "Könntest du mir mitteilen, was ich tun muss, um den nächsten Badge zu erhalten?",
        "Wie steht es um meinen Fortschritt bei den Badges?",
        "Welche Aktivitäten sind erforderlich, um den nächsten Badge zu verdienen?",
        "Was sind die Schritte, um meinen Badge-Status zu verbessern?",
        "Kannst du mir Informationen über den Fortschritt meiner Badges geben?",
        "Welche Leistungen benötige ich für den nächsten Badge?",
        "Wie kann ich meinen Badge-Status überprüfen?",
        "Was muss ich erledigen, um den nächsten Badge zu sichern?",
        "Gibt es bestimmte Aufgaben, die ich für den nächsten Badge erledigen muss?",
        "Welche Anforderungen sind für den nächsten Badge festgelegt?",
        "Wie sieht es mit meinem Fortschritt bei den Badges aus?",
        "Welche Maßnahmen kann ich ergreifen, um meinen Badge-Status zu verbessern?",
        "Kannst du mir sagen, wie ich meinen Fortschritt zu den Badges überprüfen kann?",
        "Was sind die Voraussetzungen für den nächsten Badge?",
        "Wie stehen die Chancen, meinen nächsten Badge zu erhalten?",
        "Welche Schritte sollte ich unternehmen, um den nächsten Badge zu erreichen?",
        "Kannst du mir eine Zusammenfassung meines Badge-Fortschritts geben?",
        "Welche Aktionen sind notwendig, um meinen Badge zu verbessern?",
        "Was muss ich tun, um meinen Fortschritt bei den Badges zu steigern?",
        "Welche Erfolge sind erforderlich, um den nächsten Badge zu bekommen?",
        "Wie ist mein aktueller Stand in Bezug auf die Badges?",
        "Welche Aktivitäten bringen mich dem nächsten Badge näher?",
        "Was sind die nächsten Schritte für meinen Badge-Fortschritt?",
        "Kannst du mir sagen, welche Schritte ich unternehmen muss, um meinen Badge zu verbessern?",
        "Welche Leistungen sind notwendig, um den nächsten Badge zu erhalten?",
        "Wie steht es um meinen aktuellen Badge-Status?",
        "Welche Handlungen sind notwendig, um meinen Badge zu erhöhen?",
        "Kannst du mir Details zu meinen Badge-Aktivitäten geben?",
        "Was sind die Anforderungen, um meinen nächsten Badge zu verdienen?",
        "Badge"
    ],
    UserActionType.RequestSectionSummary: [
        "Worum geht es im Abschnitt ...?",
        "Was lernt man in Abschnitt ...?",
        "Worum geht es in ...?",
        "Inhalt von ...?",
        "Fasse den Inhalt von ... zusammen",
        "Kannst du mir eine Zusammenfassung darüber geben, worum es im Abschnitt ... geht?",
        "Was wird im Modul ... behandelt?",
        "Kannst du mir sagen, was man im Abschnitt ... lernt?",
        "Was ist das Hauptthema des Moduls ...?",
        "Könntest du mir kurz erläutern, worum es im Abschnitt ... geht?",
        "Welche Inhalte werden im Modul ... abgedeckt?",
        "Kannst du mir eine kurze Übersicht darüber geben, was im Abschnitt ... behandelt wird?",
        "Was erfährt man im Modul ...?",
        "Kannst du mir zusammenfassen, worum es im Abschnitt ... geht?",
        "Was ist der Schwerpunkt im Modul ...?",
        "Kannst du mir kurz skizzieren, was im Abschnitt ... besprochen wird?",
        "Um welche Themen geht es im Modul ...?",
        "Kannst du mir in Kürze erklären, was im Abschnitt ... behandelt wird?",
        "Was sind die Hauptpunkte im Modul ...?",
        "Könntest du mir einen Überblick darüber geben, worum es im Abschnitt ... geht?",
        "Welche Konzepte werden im Modul ... vermittelt?",
        "Kannst du mir die Schlüsselideen des Abschnitts ... zusammenfassen?",
        "Was steht im Modul ... auf dem Lehrplan?",
        "Könntest du mir eine kurze Beschreibung geben, was im Abschnitt ... vorkommt?",
        "Welche Lektionen werden im Modul ... vermittelt?",
        "Kannst du mir kurz erzählen, was im Abschnitt ... abgehandelt wird?",
        "Was sind die zentralen Punkte im Modul ...?",
        "Könntest du mir einen Überblick über den Inhalt des Abschnitts ... geben?",
        "Was erwartet mich im Modul ...?",
        "Kannst du mir die Kernthemen des Abschnitts ... skizzieren?",
        "Was ist der Fokus im Modul ...?",
        "Könntest du mir kurz erläutern, worum es im Abschnitt ... geht?",
        "Was sind die Hauptinhalte des Moduls ...?",
        "Kannst du mir eine Zusammenfassung darüber geben, was im Abschnitt ... diskutiert wird?",
        "Was lernt man im Modul ... genau?",
        "Könntest du mir kurz zusammenfassen, was im Abschnitt ... enthalten ist?",
        "Was sind die Kernthemen im Modul ...?",
        "Kannst du mir einen Überblick über die Inhalte des Abschnitts ... verschaffen?",
        "Was erwartet die Teilnehmer im Modul ...?",
        "Könntest du mir kurz erklären, worum es im Abschnitt ... geht?",
        "Was sind die wichtigsten Lektionen im Modul ...?",
        "Kannst du mir zusammenfassen, was im Abschnitt ... vermittelt wird?",
        "Was sind die zentralen Ideen im Modul ...?",
        "Könntest du mir kurz darlegen, worum es im Abschnitt ... geht?",
        "Was sind die Hauptthemen des Moduls ...?",
        "Modul",
        "Abschnitt",
        "Zusammenfassen"
    ],
    UserActionType.Hello: [
        "Hallo",
        "Hi",
        "Servus",
        "Guten Tag!",
        "Hallo",
        "Hey!",
        "Wie läuft's?",
        "Wie geht's dir?",
        "Hiho!",
        "Schön, dich zu sehen!",
        "Freut mich, mit dir zu sprechen!",
        "Schön, dich kennenzulernen!",
        "Hallo, wie war dein Tag?",
        "Hi!",
        "Tag!",
        "Was gibt es zu berichten?",
        "Wie geht's, wie steht's?",
        "Schön, dass du da bist!",
        "Guten Morgen!",
        "Hallo, wie geht's dir?",
        "Wie geht's dir heute?",
        "Grüße!",
        "Grüß dich!",
        "Hallo!",
        "Hey, schön dich zu treffen!",
        "Schön dich zu sehen!",
        "Wie läuft es heute?",
        "Huhu!",
        "Hallo und willkommen zurück!",
        "Na, alles klar?",
        "Hi da!",
        "Guten Tag, wie geht es dir?",
        "Willkommen!",
        "Grüß Gott!",
        "Schön, dich hier zu haben!",
        "Willkommen zurück!",
        "Schön, dich wiederzusehen!",
        "Hey, wie geht's dir heute?",
        "Hallo und schön, dass du da bist!",
        "Aloha!",
        "Hallo, wie geht es dir heute?",
        "Guten Tag und herzlich willkommen!",
        "Hey, was hast du heute gemacht?",
        "Schön, dass du hier bist!",
        "Moin!",
        "Servus!",
        "Hallo da!",
        "Guten Abend!",
        "Hey, wie geht's?",
        "Guten Tag!"

    ],
    UserActionType.Thanks: [
        "Danke!",
        "Super, vielen Dank",
        "Dankeschön",
        "Das hat geholfen",
        "Du bist großartig, danke!",
        "Ich bin sehr erleichtert, danke!",
        "Danke, dass du mir geholfen hast!",
        "Ich bin froh, dass es dich gibt, danke!",
        "Ich bin sehr dankbar für deine Unterstützung!",
        "Ich danke dir für deine Freundlichkeit und Hilfe!",
        "Ich bin so dankbar für deine Unterstützung!",
        "Ich möchte mich bei dir bedanken!",
        "Das ist sehr nett von dir, vielen Dank!",
        "Ich danke dir für deine Freundlichkeit!",
        "Deine Hilfe hat den Unterschied gemacht, danke!",
        "Danke, das ist sehr nett!",
        "Danke für deine Mühe!",
        "Das ist sehr aufmerksam von dir, danke!",
        "Danke für deine wertvolle Zeit und Mühe!",
        "Ich danke dir für deine Geduld!",
        "Ich danke dir vielmals!",
        "Ich bin dankbar für deine Geduld!",
        "Ich kann dir gar nicht genug danken!",
        "Ich danke dir von ganzem Herzen!",
        "Ich bin so froh, dass du da bist, danke!",
        "Wow, danke!",
        "Ich danke dir für deine Hilfe!",
        "Ich danke dir für deine unendliche Geduld!",
        "Das bedeutet mir sehr viel, danke!",
        "Ich danke dir für deine Unterstützung!",
        "Ich bin dir dankbar!",
        "Ich bin dir wirklich dankbar für deine Mühe!",
        "Ich weiß deine Hilfe wirklich zu schätzen, danke!",
        "Das ist sehr großzügig von dir, vielen Dank!",
        "Das ist sehr hilfreich, danke!",
        "Großartig, danke!",
        "Das ist sehr großzügig von dir, danke!",
        "Ich bin so dankbar für deine wertvolle Unterstützung!",
        "Ich bin froh, dass du da bist!",
        "Ich bin wirklich dankbar für deine Zeit!",
        "Ich danke dir für deine Zeit!",
        "Das ist sehr nett von dir, danke!",
        "Du hast mir sehr geholfen, danke!",
        "Deine Hilfe bedeutet mir sehr viel, danke!",
        "Danke!",
        "Das ist sehr nett von dir!",
        "Tausend Dank!",
        "Ich bin wirklich erleichtert, danke!",
        "Ich schätze deine großzügige Hilfe, danke!",
        "Deine Hilfe hat mir sehr geholfen, danke!",
        "Vielen Dank!",
        "Ich schätze deine Hilfe!",
        "Ich bin dir wirklich dankbar für deine Hilfe!",
        "Super, vielen Dank!",
        "Ich danke dir aufrichtig!",
        "Vielen, vielen Dank!",
        "Ich danke dir für deine Expertise und Hilfe!",
        "Du bist großartig, danke dafür!",
        "Ich schätze deine Zeit und Mühe!",
        "Das war sehr hilfreich, vielen Dank!",
        "Ich danke dir von Herzen!",
        "Herzlichen Dank!",
        "Ich bin dir sehr dankbar für deine Hilfe!",
        "Danke für alles, was du getan hast!"

    ],
    UserActionType.LoadMoreSearchResults: [
        "Mehr Ergebnisse",
        "Weitere anzeigen",
        "Mehr laden",
        "Mehr zeigen",
        "Zeige mir bitte noch mehr Suchergebnisse, die meiner vorherigen Suche entsprechen.",
        "Ich benötige mehr Suchergebnisse, um meine Recherche zu vervollständigen. Kannst du mir bitte weiterhelfen?",
        "Gibt es noch mehr Resultate, die meiner Suche entsprechen?",
        "Könntest du mir bitte weitere passende Suchergebnisse präsentieren?",
        "Gibt es noch weitere relevante Resultate, die du mir präsentieren kannst?",
        "Könntest du mir bitte alle weiteren relevanten Ergebnisse zeigen, die zu meiner Suche passen?",
        "Zeig mir bitte alle Resultate.",
        "Kannst du mir weitere Ergebnisse zeigen?",
        "Kannst du mir bitte weitere relevante Ergebnisse zeigen?",
        "Kannst du mir bitte alle weiteren verfügbaren Suchergebnisse präsentieren?",
        "Kannst du mir bitte alle weiteren relevanten Suchergebnisse anzeigen?",
        "Gibt es noch andere passende Suchergebnisse, die ich übersehen habe?",
        "Könntest du mir bitte weitere Informationen zu diesem Thema zur Verfügung stellen, die ich noch nicht gesehen habe?",
        "Könntest du mir bitte zusätzliche Suchergebnisse zeigen?",
        "Kannst du mir weitere relevante Suchergebnisse anzeigen, die ich übersehen habe?",
        "Könntest du mir bitte weitere passende Ergebnisse präsentieren?",
        "Gibt es noch weitere relevante Informationen zu diesem Thema, die ich übersehen habe?",
        "Ich brauche noch mehr Ergebnisse, um meine Suche zu vervollständigen.",
        "Könntest du mir bitte noch weitere relevante Suchergebnisse anzeigen?",
        "Ich bin noch nicht zufrieden mit den Suchergebnissen. Könntest du mir weitere zeigen?",
        "Könntest du mir bitte noch mehr passende Ergebnisse zeigen?",
        "Ich brauche weitere Resultate.",
        "Könntest du mir bitte weitere Ergebnisse anzeigen, die meiner Suche entsprechen?",
        "Ich brauche noch mehr Ergebnisse zu meiner vorherigen Suche.",
        "Kannst du mir noch weitere relevante Suchergebnisse zeigen?",
        "Ich benötige weitere Suchergebnisse, um meine Recherche zu vervollständigen.",
        "Kannst du mir bitte alle weiteren relevanten Suchergebnisse zeigen?",
        "Ich benötige noch mehr Ergebnisse.",
        "Gibt es noch andere relevante Suchergebnisse?",
        "Ich hätte gerne weitere Suchergebnisse, um meine Suche zu erweitern.",
        "Kannst du mir bitte alle weiteren Resultate anzeigen?",
        "Könntest du mir bitte weitere relevante Suchergebnisse präsentieren?",
        "Ich möchte gerne weitere relevante Ergebnisse sehen.",
        "Könntest du mir bitte weitere relevante Suchergebnisse anzeigen?",
        "Könntest du bitte alle weiteren Ergebnisse zu diesem Thema anzeigen?",
        "Kannst du mir bitte alle verfügbaren Ergebnisse anzeigen, die meiner Suche entsprechen?",
        "Ich möchte gerne alle weiteren passenden Ergebnisse angezeigt bekommen.",
        "Könntest du mir bitte alle weiteren verfügbaren Ergebnisse anzeigen?",
        "Ich brauche mehr Ergebnisse.",
        "Ich brauche noch mehr Informationen zu meinem Thema.",
        "Kannst du mir weitere Resultate zeigen?",
        "Zeige mir bitte alle verfügbaren Ergebnisse.",
        "Ich benötige mehr Suchergebnisse.",
        "Könntest du mir bitte weitere relevante Ergebnisse anzeigen?",
        "Gibt es noch mehr Resultate, die relevant für meine Suche sind?",
        "Kannst du mir bitte weitere relevante Informationen zu diesem Thema anzeigen?",
        "Könntest du mir bitte weitere Suchergebnisse zeigen, die meiner Suche entsprechen?",
        "Gibt es noch weitere Ergebnisse, die ich überprüfen sollte?",
        "Zeige mir weitere Ergebnisse.",
        "Könntest du bitte alle weiteren verfügbaren Ergebnisse anzeigen?",
        "Zeige mir bitte alle weiteren passenden Ergebnisse.",
        "Zeig mir bitte alle weiteren verfügbaren Ergebnisse.",
        "Kannst du mir bitte noch mehr relevante Suchergebnisse zeigen?",
        "Könntest du mir bitte mehr Suchergebnisse präsentieren?",
        "Ich brauche mehr Informationen. Kannst du mir bitte weitere Ergebnisse zeigen?",
        "Zeige mir bitte alle weiteren Resultate, die meiner Suche entsprechen.",
        "Könntest du mir bitte noch mehr relevante Ergebnisse zeigen?",
        "Zeig mir bitte alle verfügbaren Resultate, die meiner Suche entsprechen.",
        "mehr",
        "Ergebnisse",
        "weitere"
    ]
}
